path:
  # --- shared
  calendar_path: E:\OneDrive\Data\Calendar\cne_calendar.csv
  root_dir: E:\OneDrive\Data\tushare
  daily_data_root_dir: E:\OneDrive\Data\tushare\by_date
  db_struct_path: E:\OneDrive\Data\tushare\db_struct.yaml
  alternative_dir: E:\OneDrive\Data\Alternative
  market_index_path: E:\OneDrive\Data\Market\index.xlsx
  by_instru_pos_dir: E:\OneDrive\Data\tushare\by_instrument\position
  by_instru_pre_dir: E:\OneDrive\Data\tushare\by_instrument\preprocess
  by_instru_min_dir: E:\OneDrive\Data\tushare\by_instrument\minute_bar

  # --- project
  project_root_dir: E:\Data\Projects\CTA_ML_Tushare
  available_dir: available
  market_dir: market
  test_return_dir: test_return
  factors_by_instru_dir: factors_by_instru
  neutral_by_instru_dir: neutral_by_instru
  feature_selection_dir: feature_selection
  mclrn_dir: mclrn
  mclrn_cfg_file: config_models.yaml
  mclrn_mdl_dir: models
  mclrn_prd_dir: predictions
  signals_dir: signals
  signals_mdl_dir: models
  signals_pfo_dir: portfolios
  simu_dir: simulations
  simu_mdl_dir: models
  simu_pfo_dir: portfolios
  eval_dir: evaluations
  eval_mdl_dir: models
  eval_pfo_dir: portfolios


mkt_idxes:
  COM: NH0100.NHF
  EQT: 881001.WI

universe:
  AU.SHF:
    sectorL0: C
    sectorL1: AUG
  AG.SHF:
    sectorL0: C
    sectorL1: AUG
  CU.SHF:
    sectorL0: C
    sectorL1: MTL
  AL.SHF:
    sectorL0: C
    sectorL1: MTL
  PB.SHF:
    sectorL0: C
    sectorL1: MTL
  ZN.SHF:
    sectorL0: C
    sectorL1: MTL
  NI.SHF:
    sectorL0: C
    sectorL1: MTL
  SN.SHF:
    sectorL0: C
    sectorL1: MTL
  SS.SHF:
    sectorL0: C
    sectorL1: MTL
  AO.SHF:
    sectorL0: C
    sectorL1: MTL
  A.DCE:
    sectorL0: C
    sectorL1: OIL
  B.DCE:
    sectorL0: C
    sectorL1: OIL
  M.DCE:
    sectorL0: C
    sectorL1: OIL
  P.DCE:
    sectorL0: C
    sectorL1: OIL
  Y.DCE:
    sectorL0: C
    sectorL1: OIL
  OI.ZCE:
    sectorL0: C
    sectorL1: OIL
  RM.ZCE:
    sectorL0: C
    sectorL1: OIL
  RU.SHF:
    sectorL0: C
    sectorL1: CHM
  BR.SHF:
    sectorL0: C
    sectorL1: CHM
  BU.SHF:
    sectorL0: C
    sectorL1: CHM
  FU.SHF:
    sectorL0: C
    sectorL1: CHM
  L.DCE:
    sectorL0: C
    sectorL1: CHM
  V.DCE:
    sectorL0: C
    sectorL1: CHM
  EB.DCE:
    sectorL0: C
    sectorL1: CHM
  EG.DCE:
    sectorL0: C
    sectorL1: CHM
  PP.DCE:
    sectorL0: C
    sectorL1: CHM
  PG.DCE:
    sectorL0: C
    sectorL1: CHM
  MA.ZCE:
    sectorL0: C
    sectorL1: CHM
  TA.ZCE:
    sectorL0: C
    sectorL1: CHM
  PF.ZCE:
    sectorL0: C
    sectorL1: CHM
  PX.ZCE:
    sectorL0: C
    sectorL1: CHM
  RB.SHF:
    sectorL0: C
    sectorL1: BLK
  HC.SHF:
    sectorL0: C
    sectorL1: BLK
  I.DCE:
    sectorL0: C
    sectorL1: BLK
  J.DCE:
    sectorL0: C
    sectorL1: BLK
  JM.DCE:
    sectorL0: C
    sectorL1: BLK
  SF.ZCE:
    sectorL0: C
    sectorL1: BLK
  SM.ZCE:
    sectorL0: C
    sectorL1: BLK
  ZC.ZCE:
    sectorL0: C
    sectorL1: BLK
  AP.ZCE:
    sectorL0: C
    sectorL1: AGR
  CF.ZCE:
    sectorL0: C
    sectorL1: AGR
  SR.ZCE:
    sectorL0: C
    sectorL1: AGR
  CY.ZCE:
    sectorL0: C
    sectorL1: AGR
  CJ.ZCE:
    sectorL0: C
    sectorL1: AGR
  PK.ZCE:
    sectorL0: C
    sectorL1: AGR
  JD.DCE:
    sectorL0: C
    sectorL1: AGR
  LH.DCE:
    sectorL0: C
    sectorL1: AGR
  C.DCE:
    sectorL0: C
    sectorL1: AGR
  CS.DCE:
    sectorL0: C
    sectorL1: AGR
  RR.DCE:
    sectorL0: C
    sectorL1: AGR

  # "UR.ZCE",
  # "FG.ZCE",
  # "SA.ZCE",
  # "SH.ZCE",
  # "SP.SHF",

available:
  win: 5
  amount_threshold: 50000.00 # unit = WANYUAN, >= 50000 WANYUAN, or 500 million
trn:
  wins: [ 60, 120, 240, 480, 720 ]
feature_selection:
  mut_info_threshold: 0.10
  min_feats: 5

# ------- database structure -------

db_struct:
  available:
    db_name: available.db
    table:
      name: available
      primary_keys:
        trade_date: TEXT
        instrument: TEXT
      value_columns:
        return: REAL
        amount: REAL
        sectorL0: TEXT
        sectorL1: TEXT
  market:
    db_name: market.db
    table:
      name: market
      primary_keys:
        trade_date: TEXT
      value_columns:
        market: REAL
        C: REAL
        AUG: REAL
        MTL: REAL
        BLK: REAL
        OIL: REAL
        CHM: REAL
        AGR: REAL
        INH0100_NHF: REAL
        I881001_WI: REAL


# ------- const -------
CONST:
  COST: 0.0003
  SECTORS: [ "AUG", "MTL", "BLK", "OIL", "CHM", "AGR" ]
  WIN: 10
  LAG: 1
  SHIFT: 11
  RET_CLASS: "010L1NEU"
  RET_NAMES: [ "ClsRtn010L1NEU", "OpnRtn010L1NEU" ]
  MAW: 10

# ------- factors -------
factors:
  MTM:
    wins: [ 20, 60, 120, 240 ]
  SKEW:
    wins: [ 20, 60, 120, 240 ]
  RS:
    wins: [ 20, 60, 120, 240 ]
  BASIS:
    wins: [ 20, 60, 120, 240 ]
  TS:
    wins: [ 20, 60, 120, 240 ]
  S0BETA: # SectorL0
    wins: [ 20, 60, 120, 240 ]
  S1BETA: # SectorL1
    wins: [ 20, 60, 120, 240 ]
  CBETA: # Currency, forex
    wins: [ 20, 60, 120, 240 ]
  IBETA: # Inflation, CPI
    wins: [ 63, 126, 252 ]
  PBETA: # PPI
    wins: [ 63, 126, 252 ]
  CTP:
    wins: [ 60, 120, 240 ]
    tops: [ 0.1, 0.2, 0.5 ]
  CTR:
    wins: [ 60, 120, 240 ]
    tops: [ 0.1, 0.2, 0.5 ]
  CVP:
    wins: [ 60, 120, 240 ]
    tops: [ 0.1, 0.2, 0.5 ]
  CVR:
    wins: [ 60, 120, 240 ]
    tops: [ 0.1, 0.2, 0.5 ]
  CSP:
    wins: [ 60, 120, 240 ]
    tops: [ 0.1, 0.2, 0.5 ]
  CSR:
    wins: [ 60, 120, 240 ]
    tops: [ 0.1, 0.2, 0.5 ]
  NOI:
    wins: [ 20, 60, 120, 240 ]
    tops: [ 5 ]
  NDOI:
    wins: [ 20, 60, 120, 240 ]
    tops: [ 5 ]
  WNOI:
    wins: [ 20, 60, 120, 240 ]
    tops: [ 5 ]
  WNDOI:
    wins: [ 20, 60, 120, 240 ]
    tops: [ 5 ]
  AMP:
    wins: [ 20, 60 ]
    lbds: [ 0.3, 0.6, 0.9 ]
  EXR:
    wins: [ 20, 40, 60 ]
    dfts: [ 3 ]
  SMT:
    wins: [ 5, 10, 20 ]
    lbds: [ 0.2, 0.4, 0.6 ]
  RWTC:
    wins: [ 5, 10, 20 ]
  TA:
    macd: [ 10, 20, 7 ]
    bbands: [ 10, 2, 2 ]
    sar: [ 0.02, 0.2 ]
    adx: 10
    bop: None
    cci: 10
    cmo: 10
    rsi: 10
    mfi: 10
    willr: 10
    adosc: [ 3, 10 ]
    obv: 10
    natr: 10

# ------- models -------
mclrn:
  #  Ridge:
  #    alpha: [ 1.0, 10.0, 100.0 ] # [1.0, 10.0, 100.0, 200.0, 500.0]
  #  LGBM:
  #    boosting_type: [ "gbdt" ]
  #    metric: [ "l2" ]
  #    max_depth: [ -1 ]
  #    num_leaves: [ 2, 4, 8 ]
  #    learning_rate: [ 0.1 ] # [0.01, 0.1, 1.0]
  #    n_estimators: [ 5, 10, 20 ] # [50, 100, 200]
  #    min_child_samples: [ 15 ] # min_data_in_leaf
  #    max_bin: [ 15 ]
  XGB:
    booster: [ "dart" ] # ["gbtree", "gblinear", "dart"]
    n_estimators: [ 5, 10, 20 ]
    max_depth: [ 2 ]
    max_leaves: [ 4 ]
    grow_policy: [ "lossguide" ] # ["depthwise", "lossguide"]
    learning_rate: [ 0.01, 0.1, 0.5 ]
    objective: [ "reg:squarederror" ]

# ------- portfolios -------
portfolios:
  P00:
    target: ClsRtn001L1RAW
    weights:
      M0155: 3 # AGR Sharpe = 0.710, Calmar = 0.681, Sharpe + Calmar = 1.391, W240, XGB, ClsRtn001L1RAW
      M0210: 1 # AUG Sharpe = 0.685, Calmar = 0.363, Sharpe + Calmar = 1.048, W480, XGB, ClsRtn001L1RAW
      M0212: 5 # BLK Sharpe = 0.694, Calmar = 0.554, Sharpe + Calmar = 1.248, W480, XGB, ClsRtn001L1RAW
      M0244: 5 # CHM Sharpe = 0.714, Calmar = 0.409, Sharpe + Calmar = 1.123, W720, XGB, ClsRtn001L1RAW
      M0205: 3 # MTL Sharpe = 0.451, Calmar = 0.230, Sharpe + Calmar = 0.681, W480, XGB, ClsRtn001L1RAW
      M0081: 3 # OIL Sharpe = 0.260, Calmar = 0.116, Sharpe + Calmar = 0.375, W120, XGB, ClsRtn001L1RAW

  P01:
    target: OpnRtn001L1RAW
    weights:
      M0389: 3 # AGR Sharpe = 1.053, Calmar = 1.255, Sharpe + Calmar = 2.308, W240, XGB, OpnRtn001L1RAW
      M0432: 1 # AUG Sharpe = 0.554, Calmar = 0.379, Sharpe + Calmar = 0.933, W480, XGB, OpnRtn001L1RAW
      M0536: 5 # BLK Sharpe = 0.710, Calmar = 0.685, Sharpe + Calmar = 1.395, W720, XGB, OpnRtn001L1RAW
      M0382: 5 # CHM Sharpe = 0.916, Calmar = 0.493, Sharpe + Calmar = 1.409, W240, XGB, OpnRtn001L1RAW
      M0463: 3 # MTL Sharpe = 0.804, Calmar = 0.608, Sharpe + Calmar = 1.413, W480, XGB, OpnRtn001L1RAW
      M0357: 3 # OIL Sharpe = 0.218, Calmar = 0.125, Sharpe + Calmar = 0.343, W120, XGB, OpnRtn001L1RAW
