path:
  # --- shared
  calendar_path: D:\OneDrive\Data\Calendar\cne_calendar.csv
  root_dir: D:\OneDrive\Data\tushare
  daily_data_root_dir: D:\OneDrive\Data\tushare\by_date
  db_struct_path: D:\OneDrive\Data\tushare\db_struct.yaml
  alternative_dir: D:\OneDrive\Data\Alternative
  market_index_path: D:\OneDrive\Data\Market\index.xlsx
  by_instru_pos_dir: D:\OneDrive\Data\tushare\by_instrument\position
  by_instru_pre_dir: D:\OneDrive\Data\tushare\by_instrument\preprocess

  # --- project
  project_root_dir: D:\OneDrive\Data\Projects\CTA_ML_Tushare
  available_dir: available
  market_dir: market

mkt_idxes:
  COM: NH0100.NHF
  EQT: 881001.WI

universe:
  AU.SHF:
    sectorL0: C
    sectorL1: AUG
  AG.SHF:
    sectorL0: C
    sectorL1: AUG
  CU.SHF:
    sectorL0: C
    sectorL1: MTL
  AL.SHF:
    sectorL0: C
    sectorL1: MTL
  PB.SHF:
    sectorL0: C
    sectorL1: MTL
  ZN.SHF:
    sectorL0: C
    sectorL1: MTL
  NI.SHF:
    sectorL0: C
    sectorL1: MTL
  SN.SHF:
    sectorL0: C
    sectorL1: MTL
  SS.SHF:
    sectorL0: C
    sectorL1: MTL
  AO.SHF:
    sectorL0: C
    sectorL1: MTL
  A.DCE:
    sectorL0: C
    sectorL1: OIL
  B.DCE:
    sectorL0: C
    sectorL1: OIL
  M.DCE:
    sectorL0: C
    sectorL1: OIL
  P.DCE:
    sectorL0: C
    sectorL1: OIL
  Y.DCE:
    sectorL0: C
    sectorL1: OIL
  OI.ZCE:
    sectorL0: C
    sectorL1: OIL
  RM.ZCE:
    sectorL0: C
    sectorL1: OIL
  RU.SHF:
    sectorL0: C
    sectorL1: CHM
  BR.SHF:
    sectorL0: C
    sectorL1: CHM
  BU.SHF:
    sectorL0: C
    sectorL1: CHM
  FU.SHF:
    sectorL0: C
    sectorL1: CHM
  L.DCE:
    sectorL0: C
    sectorL1: CHM
  V.DCE:
    sectorL0: C
    sectorL1: CHM
  EB.DCE:
    sectorL0: C
    sectorL1: CHM
  EG.DCE:
    sectorL0: C
    sectorL1: CHM
  PP.DCE:
    sectorL0: C
    sectorL1: CHM
  PG.DCE:
    sectorL0: C
    sectorL1: CHM
  MA.ZCE:
    sectorL0: C
    sectorL1: CHM
  TA.ZCE:
    sectorL0: C
    sectorL1: CHM
  PF.ZCE:
    sectorL0: C
    sectorL1: CHM
  PX.ZCE:
    sectorL0: C
    sectorL1: CHM
  RB.SHF:
    sectorL0: C
    sectorL1: BLK
  HC.SHF:
    sectorL0: C
    sectorL1: BLK
  I.DCE:
    sectorL0: C
    sectorL1: BLK
  J.DCE:
    sectorL0: C
    sectorL1: BLK
  JM.DCE:
    sectorL0: C
    sectorL1: BLK
  SF.ZCE:
    sectorL0: C
    sectorL1: BLK
  SM.ZCE:
    sectorL0: C
    sectorL1: BLK
  ZC.ZCE:
    sectorL0: C
    sectorL1: BLK
  AP.ZCE:
    sectorL0: C
    sectorL1: AGR
  CF.ZCE:
    sectorL0: C
    sectorL1: AGR
  SR.ZCE:
    sectorL0: C
    sectorL1: AGR
  CY.ZCE:
    sectorL0: C
    sectorL1: AGR
  CJ.ZCE:
    sectorL0: C
    sectorL1: AGR
  PK.ZCE:
    sectorL0: C
    sectorL1: AGR
  JD.DCE:
    sectorL0: C
    sectorL1: AGR
  LH.DCE:
    sectorL0: C
    sectorL1: AGR
  C.DCE:
    sectorL0: C
    sectorL1: AGR
  CS.DCE:
    sectorL0: C
    sectorL1: AGR
  RR.DCE:
    sectorL0: C
    sectorL1: AGR

  # "UR.ZCE",
  # "FG.ZCE",
  # "SA.ZCE",
  # "SH.ZCE",
  # "SP.SHF",

available:
  win: 5
  amount_threshold: 50000.00 # unit = WANYUAN, >= 50000 WANYUAN, or 500 million

# ------- database structure -------

db_struct:
  available:
    db_name: available.db
    table:
      name: available
      primary_keys:
        trade_date: TEXT
        instrument: TEXT
      value_columns:
        return: REAL
        amount: REAL
        sectorL0: TEXT
        sectorL1: TEXT
  market:
    db_name: market.db
    table:
      name: market
      primary_keys:
        trade_date: TEXT
      value_columns:
        market: REAL
        C: REAL
        AUG: REAL
        MTL: REAL
        BLK: REAL
        OIL: REAL
        CHM: REAL
        AGR: REAL
        INH0100_NHF: REAL
        I881001_WI: REAL

# ------- const -------
CONST:
  COST: 0.0003
  SECTORS: [ "AUG", "MTL", "BLK", "OIL", "CHM", "AGR" ]
  WIN: 10
  LAG: 1
  SHIFT: 11
  RET_CLASS: "010L1-NEU"
  RET_NAMES: [ "CloseRtn010L1-NEU", "OpenRtn010L1-NEU" ]
  MAW: 10
